"""empty message

Revision ID: 327e75f27132
Revises: c5125371b262
Create Date: 2021-05-28 22:49:40.591791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327e75f27132'
down_revision = 'c5125371b262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_usuario', sa.Column('senha_usuario', sa.String(), nullable=True))
    op.drop_column('tb_usuario', 'email_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_usuario', sa.Column('email_usuario', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tb_usuario', 'senha_usuario')
    # ### end Alembic commands ###
